; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -I include
  -D TFT_ESPI_USER_SETUP_PATH=\"tft.h\"

lib_deps =
  bblanchon/ArduinoJson@^7.4.3
  bodmer/TFT_eSPI@^2.5.43
