; PlatformIO Project Configuration File

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -I include
  -D USER_SETUP_LOADED
  -include tft_setup.h

lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  bblanchon/ArduinoJson@^7.4.3

[platformio]
default_envs = host

[env:host]
build_flags =
  ${env.build_flags}
  -D DEVICE_ROLE=ROLE_HOST

[env:client]
build_flags =
  ${env.build_flags}
  -D DEVICE_ROLE=ROLE_CLIENT
